import { supabase } from '@/lib/supabase/client'
import { Training } from '@/types/db-types'
import { storageService } from './storage-service'

export const trainingService = {
  getTrainings: async (): Promise<Training[]> => {
    const { data, error } = await supabase
      .from('trainings')
      .select('*, instructor:instructors(name)')
      .order('name')

    if (error) {
      console.error('Error fetching trainings:', error)
      return []
    }

    return data.map((t: any) => ({
      ...t,
      instructor: t.instructor?.name,
    })) as Training[]
  },

  createTraining: async (training: Partial<Training>, materialFile?: File) => {
    let materialUrl = undefined

    // Need ID for folder structure if using storageService logic based on ID,
    // but here training is not created yet.
    // Strategy: Create record, then upload, then update record OR upload with generic name/temp ID then update.
    // Better: Use a UUID generated by client or just upload after creation.
    // I'll assume basic creation first.

    // Actually, Supabase ID is generated on server.
    // Let's create the record first to get the ID.
    const { data, error } = await supabase
      .from('trainings')
      .insert(training)
      .select()
      .single()
    if (error) throw error

    if (materialFile && data) {
      try {
        materialUrl = await storageService.uploadMaterial(data.id, materialFile)
        await supabase
          .from('trainings')
          .update({ material_url: materialUrl })
          .eq('id', data.id)
      } catch (uploadError) {
        console.error('Failed to upload material', uploadError)
        // Don't fail the whole creation, just log
      }
    }

    return data
  },

  updateTraining: async (
    id: string,
    training: Partial<Training>,
    materialFile?: File,
  ) => {
    if (materialFile) {
      try {
        const materialUrl = await storageService.uploadMaterial(
          id,
          materialFile,
        )
        training.material_url = materialUrl
      } catch (uploadError) {
        console.error('Failed to upload material', uploadError)
      }
    }

    const { error } = await supabase
      .from('trainings')
      .update(training)
      .eq('id', id)
    if (error) throw error
  },
}
